# Generated by Django 6.0.2 on 2026-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(unique=True)),
                ('private_key', models.TextField(unique=True)),
                ('note', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, unique=True)),
                ('public_key', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('tx_type', models.SmallIntegerField(choices=[(1, 'REGISTER_USER'), (2, 'TRANSFER')], default=2)),
                ('height', models.IntegerField()),
                ('public_key', models.CharField(db_index=True, max_length=64)),
                ('receiver_pubkey', models.CharField(db_index=True, max_length=64, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('signature', models.CharField(max_length=128)),
                ('previous_hash', models.CharField(max_length=64)),
                ('votes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('height',), name='unique_confirmed_height')],
            },
        ),
    ]
