# Generated by Django 6.0.2 on 2026-03-04 01:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nonce', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(unique=True)),
                ('private_key', models.TextField(unique=True)),
                ('note', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, unique=True)),
                ('public_key', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('public_key', models.TextField()),
                ('signature', models.TextField()),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('votes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('height',), name='unique_confirmed_height')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(max_length=200)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identity')),
            ],
        ),
    ]
