# Generated by Django 6.0.2 on 2026-03-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='height',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
