# Generated by Django 6.0.2 on 2026-02-22 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(max_length=200)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.identity')),
            ],
        ),
    ]
