# Generated by Django 6.0.2 on 2026-03-03 04:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nonce', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(unique=True)),
                ('private_key', models.TextField(unique=True)),
                ('note', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('public_key', models.TextField()),
                ('signature', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='crypto_even_timesta_261d9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(max_length=200)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.identity')),
            ],
        ),
    ]
